WITH CTE_EMPLOYEE_DEPARTMENT AS (

SELECT EMPLOYEE_ID, 
       d.DEPARTMENT_ID,
       FIRST_NAME, 
       LAST_NAME, 
       COALESCE(DEPARTMENT_NAME, 'Unknown') AS DEPARTMENT
FROM EMPLOYEES e
LEFT JOIN DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID),

TB_DEPARTMENT AS (

SELECT DEPARTMENT_ID, 
       DEPARTMENT,
       COUNT(*) AS EMPLOYEE_COUNT
FROM CTE_EMPLOYEE_DEPARTMENT
GROUP BY DEPARTMENT_ID, DEPARTMENT
),

TB_DEPARTMENT_1 AS 
( SELECT d.*,
         ROUND(EMPLOYEE_COUNT
         /(SELECT SUM(EMPLOYEE_COUNT) FROM TB_DEPARTMENT)*100, 
         2
         ) AS PERCENTAGE
         
FROM TB_DEPARTMENT d)

SELECT tb.*,
       SUM(PERCENTAGE) OVER (
           ORDER BY PERCENTAGE DESC 
           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
       ) AS CUMULATIVE_PERCENTAGE
FROM TB_DEPARTMENT_1 tb;