WITH CTE_EMPLOYEE_DEPARTMENT AS (

    SELECT e.EMPLOYEE_ID, 
           loc.LOCATION_ID, 
           loc.COUNTRY_ID, 
           d.DEPARTMENT_ID, 
           e.FIRST_NAME, 
           e.LAST_NAME, 
           COALESCE(d.DEPARTMENT_NAME, 'Unknown') AS DEPARTMENT,
           loc.STREET_ADDRESS, 
           loc.CITY,
           loc.STATE_PROVINCE
    FROM EMPLOYEES e
    LEFT JOIN DEPARTMENTS d 
        ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    LEFT JOIN LOCATIONS loc
        ON d.LOCATION_ID = loc.LOCATION_ID
),

EMPLOYEE_COUNTRY_REGION AS (

    SELECT dl.EMPLOYEE_ID, 
           c.REGION_ID,
           c.COUNTRY_ID,
           dl.FIRST_NAME,
           dl.LAST_NAME,
           dl.CITY,
           dl.STATE_PROVINCE,
           c.COUNTRY_NAME
    FROM CTE_EMPLOYEE_DEPARTMENT dl
    LEFT JOIN COUNTRIES c
        ON dl.COUNTRY_ID = c.COUNTRY_ID
),

EMPLOYEE_REGION_COUNTRY AS (

    SELECT c.EMPLOYEE_ID,
           c.COUNTRY_ID,
           r.REGION_ID,
           c.FIRST_NAME,
           c.LAST_NAME,
           c.COUNTRY_NAME,
           r.REGION_NAME,
           COALESCE(r.REGION_NAME, 'Unknown') AS REGION_NAME_CLEAN,
           COALESCE(c.COUNTRY_NAME, 'Unknown') AS COUNTRY_NAME_CLEAN
    FROM EMPLOYEE_COUNTRY_REGION c
    LEFT JOIN REGIONS r 
        ON c.REGION_ID = r.REGION_ID
),

EMPLOYEE_COUNT_BY_COUNTRY AS (

    SELECT REGION_NAME_CLEAN,
           COUNTRY_NAME_CLEAN,
           COUNT(EMPLOYEE_ID) AS NUM_EMPLOYEE
    FROM EMPLOYEE_REGION_COUNTRY
    GROUP BY REGION_NAME_CLEAN, COUNTRY_NAME_CLEAN
)

SELECT REGION_NAME_CLEAN,
       COUNTRY_NAME_CLEAN,
       NUM_EMPLOYEE,

       SUM(NUM_EMPLOYEE) OVER (
           PARTITION BY REGION_NAME_CLEAN
       ) AS TOTAL_REGIAO,

       SUM(NUM_EMPLOYEE) OVER () AS TOTAL_EMPRESA,

       ROUND(
           NUM_EMPLOYEE 
           / SUM(NUM_EMPLOYEE) OVER (
               PARTITION BY REGION_NAME_CLEAN
             ) * 100,
           2
       ) AS PERCENTAGEM_PAIS_NA_REGIAO,

       ROUND(
           SUM(NUM_EMPLOYEE) OVER (
               PARTITION BY REGION_NAME_CLEAN
           )
           / SUM(NUM_EMPLOYEE) OVER () * 100,
           2
       ) AS PERCENTAGEM_REGIAO_NA_EMPRESA

FROM EMPLOYEE_COUNT_BY_COUNTRY
ORDER BY REGION_NAME_CLEAN, COUNTRY_NAME_CLEAN;