WITH CTE_EMPLOYEE_DEPARTMENT AS (

SELECT 
       
       e.EMPLOYEE_ID, 
       e.DEPARTMENT_ID,
       e.JOB_ID,
       e.FIRST_NAME, 
       e.LAST_NAME, 
       COALESCE(d.DEPARTMENT_NAME, 'Unknown') AS DEPARTMENT
FROM EMPLOYEES e
LEFT JOIN DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID),

EMPLOYEE_JOB AS(

SELECT 
       e.EMPLOYEE_ID, 
       e.DEPARTMENT_ID,
       e.JOB_ID,
       e.DEPARTMENT,
       j.JOB_TITLE
FROM CTE_EMPLOYEE_DEPARTMENT e
LEFT JOIN JOBS j
ON e.JOB_ID = j.JOB_ID
),

DEPATMENT_COUNT_BY_JOB_TITLE AS (SELECT DEPARTMENT,
       JOB_TITLE,
       COUNT(*) TOTAL_EMPLOYEE_BY_JOB_TITLE
FROM EMPLOYEE_JOB
GROUP BY DEPARTMENT, JOB_TITLE)

SELECT j.*,
       SUM(TOTAL_EMPLOYEE_BY_JOB_TITLE) OVER (PARTITION BY DEPARTMENT) TOTAL_EMPLOYEE_BY_DEPARTMENT,
       ROUND (
       TOTAL_EMPLOYEE_BY_JOB_TITLE/ 
       SUM(TOTAL_EMPLOYEE_BY_JOB_TITLE) OVER (PARTITION BY DEPARTMENT)*100,
       2
       ) PERCENTAGE_BY_DEPARTAMENT
FROM 
DEPATMENT_COUNT_BY_JOB_TITLE j
ORDER BY DEPARTMENT DESC, TOTAL_EMPLOYEE_BY_JOB_TITLE DESC;